dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: fsa-bcst-uhd-router-svc
  name: uhd-router-svc
  repository: https://artifactory.cluster.foxsports-gitops-prod.com.au/artifactory/helm
  version: 1.0.1
