dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- name: fsa-bcst-uhd-router-svc
  repository: https://artifactory.cluster.foxsports-gitops-prod.com.au/artifactory/helm
  version: 1.0.2
- name: ha-proxy
  alias: fsa-bcst-uhd-router-proxy
  repository: https://artifactory.cluster.foxsports-gitops-prod.com.au/artifactory/helm
  version: 0.0.2
